// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace MainMovieManager
{
	public partial class Second : NSViewController
	{
		public Second (IntPtr handle) : base (handle)
		{
		}
	}
}
